name: news_app
description: news_app

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  lint: ^2.3.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
